// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KHrNIYDiZ2AqI3hsAZRoEaGJxHYDIZg',
    appId: '1:755482642962:web:d2b77484a41e4056d6e6cb',
    messagingSenderId: '755482642962',
    projectId: 'profile-flutter-a5192',
    authDomain: 'profile-flutter-a5192.firebaseapp.com',
    storageBucket: 'profile-flutter-a5192.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wAaHVOeTWu9Svvb2endkAnEvjT6Mc1E',
    appId: '1:755482642962:android:3cfda1ed67504496d6e6cb',
    messagingSenderId: '755482642962',
    projectId: 'profile-flutter-a5192',
    storageBucket: 'profile-flutter-a5192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbQvvvW9L2KLCyhLWHxg3XxpaAWBe4BE',
    appId: '1:755482642962:ios:51e5d52c65cd66f2d6e6cb',
    messagingSenderId: '755482642962',
    projectId: 'profile-flutter-a5192',
    storageBucket: 'profile-flutter-a5192.appspot.com',
    iosClientId: '755482642962-8grfcvjv2tffm6sn3t6bubvs0nj601e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbQvvvW9L2KLCyhLWHxg3XxpaAWBe4BE',
    appId: '1:755482642962:ios:03505fef630342bcd6e6cb',
    messagingSenderId: '755482642962',
    projectId: 'profile-flutter-a5192',
    storageBucket: 'profile-flutter-a5192.appspot.com',
    iosClientId: '755482642962-22m164lpd3t48b726ek7svpc0sfjkaph.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileFlutter.RunnerTests',
  );
}
